### ISSUE TITLE
Expected http status 200, got 404 - Not Found

### ISSUE THREAD

**Issue by rebjan** [oiramalli/freshdesk-exporter#1]
Hello oiramalli,

is this exports all static data ? for example images, pdfs, docx etc, 
How can i fix following error ? 

```
$ node cli.js collect -b my_account -p 50
Starting to collect data

Saving:  tickets
{ reqOpts:
   { url: 'https://freshdesk.com/api/v2/tickets',
     method: 'GET',
     qs:
      { page: 50,
        updated_since: '2015-01-19T02:00:00Z',
        per_page: '100',
        include: 'description,requester' },
     headers:
      { Accept: 'application/json',
        Authorization: 'Basic eW91cl9hcGlrZXk6WA==' } } }
Error: Expected http status 200, got 404 - Not Found
    at Request.request [as _callback] (/home/berjan/Documents/dtcm/freshdesk/freshdesk-exporter/lib/fetcher.js:72:23)
    at Request.self.callback (/home/berjan/Documents/dtcm/freshdesk/freshdesk-exporter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/berjan/Documents/dtcm/freshdesk/freshdesk-exporter/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/berjan/Documents/dtcm/freshdesk/freshdesk-exporter/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by oiramalli** [comment]
Hi @rebjan,
For the moment this only exports all the tickets. I will update the readme file so it is not misleading.

And about the 404... Did you create a `config/local.js` file with your hostname and apikey info??
